import 'package:hive_ce/hive_ce.dart';

import '../../domain/entities/body_weight_entry.dart';
import '../../domain/entities/daily_goal.dart';
import '../../domain/entities/enums.dart';
import '../../domain/entities/program.dart';
import '../../domain/entities/user_profile.dart';
import '../../domain/entities/workout_session.dart';

part 'hive_adapters.g.dart';

/// Hive adapters for the domain entities, generated by `hive_ce_generator`.
/// Domain classes stay free of Hive annotations.
///
/// Type IDs and field indices are tracked in `hive_adapters.g.yaml`. That file
/// is the schema history: commit it, and never edit or delete it by hand.
///
/// After changing an entity, run
/// `dart run build_runner build --delete-conflicting-outputs`.
/// Only append new specs at the end of this list.
@GenerateAdapters(firstTypeId: 1, [
  AdapterSpec<UserProfile>(),
  AdapterSpec<Program>(),
  AdapterSpec<WorkoutDay>(),
  AdapterSpec<Exercise>(),
  AdapterSpec<ProgramExercise>(),
  AdapterSpec<WorkoutSession>(),
  AdapterSpec<SessionExercise>(),
  AdapterSpec<SetLog>(),
  AdapterSpec<BodyWeightEntry>(),
  AdapterSpec<MuscleGroup>(),
  AdapterSpec<ExerciseCategory>(),
  AdapterSpec<DayType>(),
  AdapterSpec<SessionStatus>(),
  AdapterSpec<ProgressionType>(),
  AdapterSpec<TrainingGoal>(),
  AdapterSpec<UnitSystem>(),
  AdapterSpec<DailyGoal>(),
  AdapterSpec<DailyGoalLog>(),
  AdapterSpec<DailyGoalType>(),
])
// ignore: unused_element
void _hiveAdapters() {}
