// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:gainit/core/storage/adapters/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BodyWeightEntryAdapter());
    registerAdapter(DayTypeAdapter());
    registerAdapter(ExerciseAdapter());
    registerAdapter(ExerciseCategoryAdapter());
    registerAdapter(MuscleGroupAdapter());
    registerAdapter(ProgramAdapter());
    registerAdapter(ProgramExerciseAdapter());
    registerAdapter(ProgressionTypeAdapter());
    registerAdapter(SessionExerciseAdapter());
    registerAdapter(SessionStatusAdapter());
    registerAdapter(SetLogAdapter());
    registerAdapter(TrainingGoalAdapter());
    registerAdapter(UnitSystemAdapter());
    registerAdapter(UserProfileAdapter());
    registerAdapter(WorkoutDayAdapter());
    registerAdapter(WorkoutSessionAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BodyWeightEntryAdapter());
    registerAdapter(DayTypeAdapter());
    registerAdapter(ExerciseAdapter());
    registerAdapter(ExerciseCategoryAdapter());
    registerAdapter(MuscleGroupAdapter());
    registerAdapter(ProgramAdapter());
    registerAdapter(ProgramExerciseAdapter());
    registerAdapter(ProgressionTypeAdapter());
    registerAdapter(SessionExerciseAdapter());
    registerAdapter(SessionStatusAdapter());
    registerAdapter(SetLogAdapter());
    registerAdapter(TrainingGoalAdapter());
    registerAdapter(UnitSystemAdapter());
    registerAdapter(UserProfileAdapter());
    registerAdapter(WorkoutDayAdapter());
    registerAdapter(WorkoutSessionAdapter());
  }
}
